### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by chiwunau** [iKrishneel/ros_cv_pkg#16]
100 : initial-segmentatoin
010 : robot move
001 :final segmentation

**Comment by iKrishneel** [comment]
Also keep a internal global counter of type int starting at 0. The signal.msg has a field counter which should be incremented after successful processing.

**Comment by chiwunau** [comment]
Topic names:

### from the motion node
- std_msgs::Int64
  -  /robot_pushing_motion_node/pushed_box_index 
- geometry_msgs::PoseStamped
  - /robot_pushing_motion_node/pushed_box_assumed_pose

**Comment by iKrishneel** [comment]
Signal Topic of the first node (initial segmentation node)
- /scene_decomposer/output/signal

**Comment by iKrishneel** [comment]
Please use the command as follows: 

1 - Segmentation
2 - Robot Movement
3 - Final Object Assembly

All of type int64

**Comment by chiwunau** [comment]
close for humanoids published
